version: 2

jobs:
  build:
    working_directory: ~/work

    docker:
      - image: circleci/openjdk:8

    steps:
      - checkout

      - restore_cache:
          key: cache-{{ checksum "build.gradle" }}-{{ checksum "gradle" }}

      - run: ./gradlew build

      - save_cache:
          paths:
            - ~/.gradle
          key: cache-{{ checksum "build.gradle" }}-{{ checksum "gradle" }}

      - store_test_results:
          path: build/test-results
