version: 2
jobs:
  build:
    docker:
      - image: docker

    working_directory: ~/repo

    steps:
      - checkout

      - run: |
          docker build -t adeln/youtube .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push adeln/youtube
